module.exports = {
	"validationError": "Validation Error Please check params.",
	"ServerError": "Server Error We'll try to fix this as soon as possible.",
	"NoResultFound": "No record found",
	"AuthorizationError": "You are not authorized to perform this action.",
	"AuthenticationError": "Invalid userName or email address.",
	"PasswordError": "Invalid password.",
	"AuthenticationSuccessfully": "Password Authenticated successfully",
	"DisabledByAdmin": "Account disable by admin, Please contact admin.",
	"DeletedByAdmin": "Account has been delete by admin.",
	"BadRequest": "Please check params to perform action.",
	"BodyMissing": "Request body missing.",
	"EmailMissing": "Email is missing.",
	"RequiredFiledMissing": "Required params are missing. Please check it once.",
	"UsernameMissing": "Username is missing.",
	"DeviceIdMissing": "Device id is missing.",
	"PasswordMissing": "Password is missing",
	"DeviceTypeMissing": "Device type is missing",
	"AlreadyExists": "Either userName or Email already exists. Please check it once. Thanks!!!",
	"RecordCreated": "Record created successfully.",
	"RecordUpdated": "Record Updated successfully.",
	"PasswordUpdated": "Password updated successfully.",
	"UserFetched": "Users fetched successfully",
	"NoRecordWithCredentails": "No record found to update with this credentails"
};